[package]
name = "rust_practice"
version = "0.1.0"
authors = ["kai <iamzko@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
